var namespace_k_a_g_o__framework_1_1model_1_1abitur_1_1datenbanken_1_1mysql =
[
    [ "DatabaseConnector", "class_k_a_g_o__framework_1_1model_1_1abitur_1_1datenbanken_1_1mysql_1_1_database_connector.html", "class_k_a_g_o__framework_1_1model_1_1abitur_1_1datenbanken_1_1mysql_1_1_database_connector" ],
    [ "QueryResult", "class_k_a_g_o__framework_1_1model_1_1abitur_1_1datenbanken_1_1mysql_1_1_query_result.html", "class_k_a_g_o__framework_1_1model_1_1abitur_1_1datenbanken_1_1mysql_1_1_query_result" ]
];